application: seungjin-net
version: 1
runtime: python
api_version: 1

handlers:
- url: /.*
  script: view.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin